# Site settings
name: Eashan Mathur
title: Eashan Mathur
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://eashanmathur.com/
baseurl: ''
email: brittany.chiang@gmail.com
cover: https://eashanmathur.com/img/og.png
logo: https://eashanmathur.com/img/emojis/technologist.png
resume: https://beashanmathur.com/resume.pdf
social:
  - title: email
    url: mailto:brittany.chiang@gmail.com
  - title: instagram
    url: https://instagram.com/eashan.mathur
  - title: github
    url: https://github.com/eashan-mathur
  - title: linkedin
    url: https://www.linkedin.com/in/eashan-mathur

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

gems:
- jekyll-seo-tag

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
